cc_test(
    name = "bounded_buffer",
    srcs = ["bounded_buffer_test.cpp"],
    copts = [
        "-Iinclude",
        "-Iexternal/gtest/include",
    ],
    deps = [
        "@gtest//:main",
        "//include:bounded_buffer",
    ],
)
