cc_test(
    name = "bounded_buffer",
    srcs = ["bounded_buffer_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//src:bounded_buffer",
    ],
)
