language: cpp
sudo: required
dist: bionic
os: linux
compiler: g++

notifications:
    email: false

addons:
  apt:
    update: true
    packages:
      - googletest
      - libgtest-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cd /usr/src/googletest
  - sudo cmake .
  - sudo cmake --build . --target install
  - apt list --installed | grep "googletest"
  - apt list --installed | grep "libgtest-dev"

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

script: ./tests

env:
  global:
    - LC_ALL="en_US.UTF-8"
