language: cpp
sudo: required
dist: bionic
os: linux
compiler: g++

notifications:
    email: false

addons:
  apt:
    update: true
    packages:
      - googletest
      - libgtest-dev
      - cmake

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cmake --version
  - cd /usr/src/googletest
  - sudo cmake .
  - sudo cmake --build . --target install
  - cd -

script: ./test.sh

env:
  global:
    - LC_ALL="en_US.UTF-8"
