language: cpp
sudo: required
dist: bionic
os: linux
compiler: g++

notifications:
    email: false

addons:
  apt:
    update: true
    packages:
      - googletest
      - libgtest-dev
      - cmake
      - lcov

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cmake --version
  - cd /usr/src/googletest
  - sudo cmake .
  - sudo cmake --build . --target install
  - cd -

script: ./test.sh

after_script:
  # Create lcov coverage report.
  - lcov --directory . --capture --output-file coverage.info
  # Remove entries about system and other files.
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  # Print coverage data.
  - lcov --list coverage.info
  # Upload coverage info to Codecov.
  - bash <(curl -s https://codecov.io/bash) -f bounded_buffer.hpp.gcov || echo "Codecov did not collect coverage results"

env:
  global:
    - LC_ALL="en_US.UTF-8"
